### ISSUE TITLE
Create a Hero component for Home page and Detail page

### ISSUE THREAD

**Issue by ronaldpaek** [chingu-voyages/v42-geckos-team-23#18]
**__User Story Description__**
As a user
I want to be able to see some placeholder images
So I can stay engaged

**__Steps to Follow__**
- [ ] Import a title for a hero section in Home page #35
- [ ] Import a Carousel component for hero sections in Home page and Detail page #37
- [ ] Find and store images for a hero section in Home page #36
- [ ] Fetch business images from YelpAPIInterface component in Detail page #44 

**__Additional Considerations__**
- Must be responsive 
- Image should span 100vh

![Screenshot 2023-01-14 at 8.24.19 PM.png](https://images.zenhubusercontent.com/63af8af4ad64054b2f8d8eaf/94db6c6a-70f9-4fb0-ab44-ae04a2f40cee)

![Screen Shot 2023-01-17 at 5 31 42 PM](https://user-images.githubusercontent.com/52467273/213059106-84c08aa2-57e2-4d09-bd46-316b71881ab5.png)

**Member of Epic:** #19
