### ISSUE TITLE
Create contextProvider to manage project state

### ISSUE THREAD

**Issue by ronaldpaek** [chingu-voyages/v42-geckos-team-23#22]
**__Task Description__**
Create contextProvider to manage project state using react hook use context.

**__Technical Considerations__**
Required states:
- [ ] Zipcode (Initial popup window and navbar share this state)

- [ ] Category (Initial popup window and navbar share this state)

- [ ] Data from the search results once the user clicks the search button

**__Additional Considerations__**

**Member of Epic:** #19
