### ISSUE TITLE
Create a SearchForm component for navbar and popup window

### ISSUE THREAD

**Issue by ronaldpaek** [chingu-voyages/v42-geckos-team-23#31]
**__Task Description__**
- [ ] Create zip code search input
- [ ] Create a subtitle that appears depending on the state
- [ ] Create categories radio buttons for search
- [ ] Import a Button component for search #45 

**__Technical Considerations__**
When a user clicks a search button, it fetches business results from Yelp API #44 
onChange should update the zip codes state (it should reference the initial popup window).
onChange should update the categories state (it should reference the initial pup window).
Give style variation depending on a section.
 
**__Additional Considerations__**
![Screenshot 2023-01-14 at 8.16.46 PM.png](https://images.zenhubusercontent.com/63af8af4ad64054b2f8d8eaf/a73bd35d-333f-4866-8409-3f46a6b6a78b)

![image](https://user-images.githubusercontent.com/52467273/213037839-30841096-fdc5-4d39-8847-83d021dfc632.png)

**Member of Issue:** #21
