### ISSUE TITLE
 Create a search form for the pop-up window

### ISSUE THREAD

**Issue by ronaldpaek** [chingu-voyages/v42-geckos-team-23#34]
**__Task Description__**
- [ ] Create search input for a zipcode
- [ ] Create a subtitle
- [ ] Create categories checkboxes
- [ ] Create a search button

**__Technical Considerations__**
Follow the Figma design.

**__Additional Considerations__**
![Screenshot 2023-01-14 at 8.19.38 PM.png](https://images.zenhubusercontent.com/63af8af4ad64054b2f8d8eaf/ccbb01e9-cb15-4f05-9b7d-43c296dc17fc)

**Member of Issue:** #15
