### ISSUE TITLE
Create a Results component 

### ISSUE THREAD

**Issue by ronaldpaek** [chingu-voyages/v42-geckos-team-23#38]
**__User Story Description__**
As a User
I want to be able to see my results in a list
So I can quickly look at pet-friendly restaurants near me.

**__Steps to Follow__**
- [ ] Import a title for a Results component #39
- [ ] Import Card components #24
- [ ] Import a Pagination component #40 

**__Additional Considerations__**
- Display Card component in a 3-column layout in a desktop version, and in a 1-column layout in a mobile version.

![Screenshot 2023-01-14 at 8.27.59 PM.png](https://images.zenhubusercontent.com/63af8af4ad64054b2f8d8eaf/e546a27e-fd86-4a6a-9a13-b32336f5e8d0)

**Member of Epic:** #19
