### ISSUE TITLE
Create a YelpAPI component

### ISSUE THREAD

**Issue by jiyunnoh** [chingu-voyages/v42-geckos-team-23#44]
**__Task Description__**
- [x] Create a group email to get a Yelp API key
- [x] Create a method for searching business
- [x] Create a method for getting business detail by Id (including 3 photos) -> (How are we going to cover in case a business has less than 3 images? Showing default images? )
- [x] Create a method for getting reviews by business Id

**__Technical Considerations__**

**__Additional Considerations__**
- Link to Yelp API : https://docs.developer.yelp.com/docs/fusion-intro
