### ISSUE TITLE
Create a Button component

### ISSUE THREAD

**Issue by jiyunnoh** [chingu-voyages/v42-geckos-team-23#45]
**__Task Description__**

- [ ] Create a small search button and for mobile design
- [ ] Create a big search button and for mobile design
- [ ] Create a white bg button and for mobile design

**__Technical Considerations__**

**__Additional Considerations__**
![Screen Shot 2023-01-17 at 4.15.31 PM.png](https://images.zenhubusercontent.com/63bb586e72c937e7a9e07ede/7558a018-e637-413f-91aa-59b7cc800d71)

![Screen Shot 2023-01-17 at 4.15.49 PM.png](https://images.zenhubusercontent.com/63bb586e72c937e7a9e07ede/064c641d-acd0-4ebf-a2b4-16f2cd4968b2)

![Screen Shot 2023-01-17 at 4.16.15 PM.png](https://images.zenhubusercontent.com/63bb586e72c937e7a9e07ede/9406e632-9159-48b0-ba90-ddbd0e90a8bf)
