### ISSUE TITLE
Create a Detail component

### ISSUE THREAD

**Issue by jiyunnoh** [chingu-voyages/v42-geckos-team-23#47]
**__Task Description__**
This component shows:
- [ ] business name
- [ ] mini map (takes user to google maps)
- [ ] business address
- [ ] website (takes user to business web page)
- [ ] business phone number
- [ ] yelp page(takes user to business yelp page)

**__Technical Considerations__**
Data will be fetched from Yelp API #44 

**__Additional Considerations__**

![Screen Shot 2023-01-17 at 11 01 05 PM](https://user-images.githubusercontent.com/52467273/213105375-3e4bf84f-8b0b-46ad-b21f-6d596ecca49c.png)
